application: khanexercises
version: 1
runtime: python
api_version: 1
default_expiration: "14d"

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript

- url: /helperpages
  static_dir: helperpages
  
  # The url below needs to be updated whenever we change/upgrade MathJax.
  # Unfortunately, we can't use a regex due to a GAE bug:
  # http://code.google.com/p/googleappengine/issues/detail?id=3380
- url: /MathJax-svn382
  static_dir: MathJax

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin  

- url: .*
  script: main.py
  


