application: khanexercises
version: 764
runtime: python
api_version: 1
default_expiration: "14d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?sample_data/.*

handlers:
- url: /videos
  static_dir: offline/Khan Academy/videos
  
- url: /flvplayer
  static_dir: flvplayer

- url: /stylesheets
  static_dir: stylesheets
  
- url: /images/favicon.ico
  static_files: images/favicon.ico
  mime_type: image/x-icon
  upload: images/favicon.ico

- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript

- url: /helperpages/d\.svg
  static_files: helperpages/d.svg
  upload: helperpages/d\.svg
  mime_type: image/svg+xml

- url: /helperpages
  static_dir: helperpages
  
- url: /downloads/(.*)
  static_files: downloads/\1
  upload: downloads/(.*)
  
  # The url below needs to be updated whenever we change/upgrade MathJax.
  # Unfortunately, we can't use a regex due to a GAE bug:
  # http://code.google.com/p/googleappengine/issues/detail?id=3380
- url: /MathJax-svn382
  static_dir: MathJax

  # The url below needs to be updated whenever we change/upgrade svg-edit.
  # We use our own version of the svg-editor.html file
- url: /svg-edit-[^/]*/svg-editor\.html
  static_files: helperpages/svg-editor.html
  upload: helperpages/svg-editor.html
  
  # Make sure we serve the svg files with the correct mime-type.
- url: /svg-edit-[^/]*/(.*)\.svg
  static_files: svg-edit/\1.svg
  upload: svg-edit/(.*)\.svg
  mime_type: image/svg+xml

  # All the other svg-editor bits are stock.
  # The url below needs to be updated whenever we change/upgrade svg-edit.
  # Unfortunately, we can't use a regex due to a GAE bug:
  # http://code.google.com/p/googleappengine/issues/detail?id=3380
- url: /svg-edit-2.5-khan-120310-3
  static_dir: svg-edit

  # The url below needs to be updated whenever we change/upgrade Jit.
  # Unfortunately, we can't use a regex due to a GAE bug:
  # http://code.google.com/p/googleappengine/issues/detail?id=3380
- url: /Jit-2.0.0a
  static_dir: Jit

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin  

- url: /admin/.*
  script: main.py
  login: admin

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: .*
  script: main.py
  


